package provision

import (
	"testing"

	"github.com/MikD1/agent-vm/internal/config"
)

func TestRenderMiseConfig(t *testing.T) {
	got := string(renderMiseConfig([]config.ModuleSpec{
		{Name: "node", Version: "lts"},
		{Name: "go", Version: "1.24"},
		{Name: "npm:@openai/codex", Version: "latest"},
	}))
	want := `# Generated by avm. Do not edit: change .agent-vm.yaml and run ` + "`avm recreate`" + `.
[tools]
"node" = "lts"
"go" = "1.24"
"npm:@openai/codex" = "latest"
`
	if got != want {
		t.Errorf("renderMiseConfig() =\n%s\nwant\n%s", got, want)
	}
}

func TestRenderMiseConfigEmpty(t *testing.T) {
	got := string(renderMiseConfig(nil))
	want := `# Generated by avm. Do not edit: change .agent-vm.yaml and run ` + "`avm recreate`" + `.
[tools]
`
	if got != want {
		t.Errorf("renderMiseConfig(nil) =\n%s\nwant\n%s", got, want)
	}
}
