package provision

import (
	"bytes"
	"encoding/json"
	"fmt"
	"path"
	"sort"

	"github.com/MikD1/agent-vm/internal/config"
)

// miseDataDir is where mise installs tools and shims. It is deliberately outside
// any user's home: tools must be visible to the VM user, to root, and under sudo,
// which is what the current system-wide module installs give.
const miseDataDir = "/usr/local/share/mise"

// miseShims is the directory the shim symlinks live in.
const miseShims = miseDataDir + "/shims"

// miseConfigPath is mise's documented system-wide config, applying to all users.
const miseConfigPath = "/etc/mise/config.toml"

// renderMiseConfig writes the [tools] table in spec order. Tool names are always
// quoted so that backend references like "npm:@openai/codex" need no special
// case. Only plain version strings are emitted, which mise treats as a "safe"
// config requiring no trust — so provisioning cannot block on a prompt.
func renderMiseConfig(mods []config.ModuleSpec) []byte {
	var b bytes.Buffer
	b.WriteString("# Generated by avm. Do not edit: change agent-vm.yaml and run `avm recreate`.\n")
	b.WriteString("[tools]\n")
	for _, m := range mods {
		fmt.Fprintf(&b, "%q = %q\n", m.Name, m.Version)
	}
	return b.Bytes()
}

// renderMiseInstall is the phase 3 script: write the system config, then install
// every tool in one mise invocation. mise resolves its own ordering and
// parallelizes downloads, so there is no per-module loop.
//
// MISE_DATA_DIR is exported here because lima.Provision's wrapper only exports
// the VM_* contract. `mise reshim` runs afterwards so the shim directory is
// populated even when a backend skips creating shims itself.
func renderMiseInstall(mods []config.ModuleSpec, verbose bool) []byte {
	flags := "-y"
	if verbose {
		flags = "-y --verbose"
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, "export MISE_DATA_DIR=%s\n", miseDataDir)
	fmt.Fprintf(&b, "install -d -m 0755 %s\n", path.Dir(miseConfigPath))
	// A quoted heredoc delimiter: nothing in the config body is expanded. No tool
	// name can contain the delimiter — the module reference regex forbids it.
	fmt.Fprintf(&b, "cat > %s <<'AVM_MISE_CONFIG_EOF'\n", miseConfigPath)
	b.Write(renderMiseConfig(mods))
	b.WriteString("AVM_MISE_CONFIG_EOF\n")
	fmt.Fprintf(&b, "mise install %s\n", flags)
	b.WriteString("mise reshim\n")
	return b.Bytes()
}

// parseMiseList reads `mise ls -i -J` — an object keyed by tool name, each value
// a list of installed versions — and flattens it to one entry per tool, sorted by
// name so the Record is byte-stable between runs.
func parseMiseList(out []byte) ([]config.ModuleSpec, error) {
	var raw map[string][]struct {
		Version string `json:"version"`
	}
	if err := json.Unmarshal(out, &raw); err != nil {
		return nil, fmt.Errorf("parse `mise ls` output: %w", err)
	}
	installed := make([]config.ModuleSpec, 0, len(raw))
	for name, versions := range raw {
		if len(versions) == 0 {
			continue
		}
		installed = append(installed, config.ModuleSpec{Name: name, Version: versions[0].Version})
	}
	sort.Slice(installed, func(i, j int) bool { return installed[i].Name < installed[j].Name })
	return installed, nil
}
