package provision

import (
	"bytes"
	"fmt"

	"github.com/MikD1/agent-vm/internal/config"
)

// miseDataDir is where mise installs tools and shims. It is deliberately outside
// any user's home: tools must be visible to the VM user, to root, and under sudo,
// which is what the current system-wide module installs give.
const miseDataDir = "/usr/local/share/mise"

// miseShims is the directory the shim symlinks live in.
const miseShims = miseDataDir + "/shims"

// miseConfigPath is mise's documented system-wide config, applying to all users.
const miseConfigPath = "/etc/mise/config.toml"

// renderMiseConfig writes the [tools] table in spec order. Tool names are always
// quoted so that backend references like "npm:@openai/codex" need no special
// case. Only plain version strings are emitted, which mise treats as a "safe"
// config requiring no trust — so provisioning cannot block on a prompt.
func renderMiseConfig(mods []config.ModuleSpec) []byte {
	var b bytes.Buffer
	b.WriteString("# Generated by avm. Do not edit: change .agent-vm.yaml and run `avm recreate`.\n")
	b.WriteString("[tools]\n")
	for _, m := range mods {
		fmt.Fprintf(&b, "%q = %q\n", m.Name, m.Version)
	}
	return b.Bytes()
}
